version: "3"
services:
  web:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      PORT: "9292"
    ports:
      - "9292:9292"
    command: "rackup -o 0.0.0.0 -p 9292"
volumes:
  bundle:
